### ISSUE TITLE
Why GZip Before Cyher?

### ISSUE THREAD

**Issue by F1LT3R** [bbstilson/node-encryption#6]
Hey @bbstilson - nice code, thanks!

Quick question, why GZIP before Cypher?

Is this just for performance?

**Comment by bbstilson** [comment]
Yep, speed. Fewer bytes to encrypt.

**Comment by F1LT3R** [comment]
BTW: A quick wrapper for CLI usage...

https://github.com/f1lt3r/node-encryption
